// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/2/10 19:09:54
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/hulian/Desktop/huliang/bolg/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/plugins/**/*.{js,ts,mjs}","C:/Users/hulian/Desktop/huliang/bolg/blog/composables/**/*.{js,ts,mjs}","C:/Users/hulian/Desktop/huliang/bolg/blog/utils/**/*.{js,ts,mjs}","C:/Users/hulian/Desktop/huliang/bolg/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hulian/Desktop/huliang/bolg/blog/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;